#!/bin/bash

TESTS_THAT_NEED_FIX=" \
test_arithmetic_expr or \
test_arithmetic_expr_left_literal or \
test_cast or \
test_cast_binary or \
test_cast_datetime_tz_aware or \
test_cast_datetime_utc or \
test_cast_raises_for_unknown_dtype or \
test_cast_time or \
test_cast_to_enum_v1 or \
test_cast_to_enum_vmain or \
test_categorical or \
test_ceil_expr or \
test_clip_expr or \
test_clip_expr_expressified or \
test_coalesce_multi_output or \
test_coalesce_numeric or \
test_coalesce_strings or \
test_concat_str or \
test_concat_str_with_lit or \
test_concat_vertical or \
test_contains_case_insensitive or \
test_contains_case_sensitive or \
test_contains_expr or \
test_contains_literal or \
test_convert_time_zone or \
test_convert_time_zone_from_none or \
test_datetime or \
test_datetime_attributes or \
test_diff_lazy or \
test_diff_lazy_grouped or \
test_drop_nulls_agg or \
test_dt_to_string_expr or \
test_dt_to_string_iso_local_date_expr or \
test_dt_to_string_iso_local_datetime_expr or \
test_duration_attributes or \
test_empty_scalar_reduction_with_columns or \
test_ends_with or \
test_exp_expr or \
test_explode_invalid_operation_error or \
test_explode_multiple_cols or \
test_explode_shape_error or \
test_explode_single_col or \
test_expr_binary or \
test_expr_floordiv_by_zero or \
test_expr_rfloordiv_by_zero or \
test_fill_nan or \
test_fill_null_limits or \
test_fill_null_strategies_with_limit_as_none or \
test_fill_null_strategies_with_partition_by or \
test_filter or \
test_filter_missing_column or \
test_first_expr_over_order_by or \
test_first_expr_over_order_by_partition_by or \
test_floor_expr or \
test_format or \
test_get_expr or \
test_get_field_expr or \
test_group_by_categorical or \
test_group_by_median or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_scalar or \
test_is_finite_expr or \
test_joinasof_by or \
test_joinasof_numeric or \
test_joinasof_suffix or \
test_joinasof_time or \
test_kurtosis_expr or \
test_lazy_cum_prod_grouped or \
test_lazy_rank_expr or \
test_lazy_rank_expr_desc or \
test_left_to_right_broadcasting or \
test_len_expr or \
test_mapping_key_not_in_expr or \
test_median_expr or \
test_median_expr_raises_on_str or \
test_missing_columns or \
test_mode_expr_keep_all_lazy or \
test_mode_expr_keep_any or \
test_mode_group_by_multimodal or \
test_mode_group_by_multiple_cols or \
test_mode_group_by_unimodal or \
test_n_unique_over or \
test_namespace_from_native_object or \
test_nan or \
test_nan_non_float or \
test_native_namespace_frame or \
test_offset_by or \
test_offset_by_dst or \
test_offset_by_invalid_interval or \
test_offset_by_tz or \
test_order_dependent_raises_in_lazy or \
test_over_anonymous_reduction or \
test_over_pushdown or \
test_over_quantile or \
test_over_std_var or \
test_package_version or \
test_parse_weight or \
test_pipe_expr or \
test_quantile_expr or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_desc or \
test_rank_with_order_by or \
test_rank_with_order_by_and_partition_by or \
test_replace_strict_expr_basic or \
test_replace_strict_expr_with_default or \
test_replace_strict_non_full or \
test_replace_strict_with_default_and_nulls or \
test_replace_strict_with_default_mapping or \
test_replace_strict_with_expressified_default or \
test_replace_time_zone or \
test_replace_time_zone_none or \
test_right_arithmetic_expr or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_select_duplicates or \
test_set_ops or \
test_shift_lazy or \
test_shift_lazy_grouped or \
test_skew_expr or \
test_split_list_get or \
test_sqrt_expr or \
test_starts_with or \
test_std_broadcating or \
test_str_head or \
test_str_len_chars or \
test_str_replace_all_expr_multivalue or \
test_str_replace_all_expr_scalar or \
test_str_replace_errors_expr or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_scalar or \
test_str_slice or \
test_str_split or \
test_str_strip_chars or \
test_str_tail or \
test_str_to_lowercase or \
test_str_to_titlecase_expr or \
test_str_to_uppercase or \
test_str_zfill or \
test_sumh_broadcasting or \
test_sumh_transformations or \
test_timestamp_dates or \
test_timestamp_datetimes or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_invalid_date or \
test_to_date or \
test_to_date_infer_fmt_expr or \
test_to_date_with_fmt_expr or \
test_to_datetime or \
test_to_datetime_infer_fmt or \
test_to_datetime_infer_fmt_from_date or \
test_to_datetime_tz_aware or \
test_top_k or \
test_top_k_by_multiple or \
test_truncate or \
test_truncate_invalid_interval or \
test_truncate_invalid_multiple or \
test_truncate_multiples or \
test_tz_aware or \
test_unary or \
test_unique or \
test_unique_3069 or \
test_unique_expr or \
test_unique_expr_agg or \
test_unique_full_subset or \
test_unique_invalid or \
test_unique_none or \
test_when_then_broadcasting or \
test_when_then_otherwise_aggregate_with_columns or \
test_with_columns_dtypes_single_row or \
test_with_columns_missing_column \
"

pytest narwhals/tests \
  -p pytest_constructor_override \
  -p env \
  --use-external-constructor \
  --constructors daft \
  -k "not ( \
      ${TESTS_THAT_NEED_FIX} \
  )" \
  "$@"
