#!/bin/bash

TESTS_THAT_NEED_FIX=" \
test_abs or \
test_add or \
test_alias_invalid or \
test_all_ignore_nulls or \
test_all_kind_of_aggs or \
test_allh or \
test_allh_all or \
test_allh_iterator or \
test_allh_kleene or \
test_allh_nth or \
test_anti_join or \
test_any_all or \
test_anyh or \
test_anyh_all or \
test_anyh_ignore_nulls or \
test_anyh_kleene or \
test_arithmetic_expr or \
test_arithmetic_expr_left_literal or \
test_boolean or \
test_cast or \
test_cast_binary or \
test_cast_datetime_tz_aware or \
test_cast_datetime_utc or \
test_cast_raises_for_unknown_dtype or \
test_cast_struct or \
test_cast_time or \
test_cast_to_enum_v1 or \
test_cast_to_enum_vmain or \
test_categorical or \
test_ceil_expr or \
test_clip_expr or \
test_clip_expr_expressified or \
test_clip_invalid or \
test_coalesce_multi_output or \
test_coalesce_numeric or \
test_coalesce_raises_non_expr or \
test_coalesce_strings or \
test_collect_empty or \
test_collect_schema or \
test_collect_to_default_backend or \
test_collect_to_invalid_backend or \
test_collect_to_valid_backend_pyarrow or \
test_collect_to_valid_backend_pyarrow_mod or \
test_collect_with_kwargs or \
test_columns or \
test_comparand_operators_expr or \
test_comparand_operators_scalar_expr or \
test_concat_diagonal or \
test_concat_str or \
test_concat_str_with_lit or \
test_concat_vertical or \
test_contains_case_insensitive or \
test_contains_case_sensitive or \
test_contains_expr or \
test_contains_literal or \
test_convert_time_zone or \
test_convert_time_zone_from_none or \
test_convert_time_zone_to_none or \
test_count or \
test_cross_join or \
test_cross_join_suffix or \
test_datetime or \
test_datetime_attributes or \
test_datetime_no_tz or \
test_diff_lazy or \
test_diff_lazy_grouped or \
test_double or \
test_double_alias or \
test_double_same_aggregation or \
test_double_selected or \
test_drop or \
test_drop_nulls or \
test_drop_nulls_agg or \
test_drop_nulls_subset or \
test_drop_strict or \
test_dt_to_string_expr or \
test_dt_to_string_iso_local_date_expr or \
test_dt_to_string_iso_local_datetime_expr or \
test_duration_attributes or \
test_empty_scalar_reduction_select or \
test_empty_scalar_reduction_with_columns or \
test_ends_with or \
test_eq_neq_raise or \
test_exclude or \
test_exp_expr or \
test_explode_invalid_operation_error or \
test_explode_multiple_cols or \
test_explode_shape_error or \
test_explode_single_col or \
test_expr_binary or \
test_expr_floordiv_by_zero or \
test_expr_is_in or \
test_expr_is_in_empty_list or \
test_expr_max_expr or \
test_expr_mean_expr or \
test_expr_min_expr or \
test_expr_rfloordiv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_sum_expr or \
test_expr_truediv_by_zero or \
test_fancy_functions or \
test_fill_nan or \
test_fill_null or \
test_fill_null_exceptions or \
test_fill_null_limits or \
test_fill_null_series_expression or \
test_fill_null_strategies_with_limit_as_none or \
test_fill_null_strategies_with_partition_by or \
test_fill_null_w_aggregate or \
test_filter or \
test_filter_constraints or \
test_filter_is_between or \
test_filter_missing_column or \
test_filter_multiple_predicates or \
test_filter_raise_on_agg_predicate or \
test_filter_raise_on_shape_mismatch or \
test_filter_seq_iterable_all_false or \
test_filter_seq_iterable_all_true or \
test_filter_string_predicate or \
test_filter_with_boolean_list_predicates_lazy or \
test_filter_with_constrains_only or \
test_filter_with_expr_predicates or \
test_first_expr_over_order_by or \
test_first_expr_over_order_by_partition_by or \
test_floor_expr or \
test_format or \
test_from_dict_without_backend_invalid or \
test_full_join or \
test_full_join_duplicate or \
test_get_expr or \
test_get_expr_negative_index or \
test_get_expr_non_int_index or \
test_get_field_expr or \
test_group_by_categorical or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg_bool_ops or \
test_group_by_depth_1_std_var or \
test_group_by_expr or \
test_group_by_len_1_column or \
test_group_by_median or \
test_group_by_multiple_keys or \
test_group_by_n_unique_w_missing or \
test_group_by_nw_all or \
test_group_by_raise_drop_null_keys_with_exprs or \
test_group_by_raise_if_not_preserves_length or \
test_group_by_selector or \
test_group_by_shift_raises or \
test_group_by_simple_named or \
test_group_by_simple_unnamed or \
test_group_by_window or \
test_head or \
test_horizontal_expressions_empty or \
test_inner_join_single_key or \
test_inner_join_two_keys or \
test_invalid_operations or \
test_invalid_select or \
test_is_between or \
test_is_between_datetimes or \
test_is_between_expressified or \
test_is_between_invalid or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_scalar or \
test_is_duplicated_expr or \
test_is_duplicated_w_nulls_expr or \
test_is_finite_column_with_null or \
test_is_finite_expr or \
test_is_finite_integer_column or \
test_is_first_distinct_expr_lazy or \
test_is_first_distinct_expr_lazy_grouped or \
test_is_in_other or \
test_is_last_distinct_expr_lazy or \
test_is_last_distinct_expr_lazy_grouped or \
test_is_last_distinct_expr_lazy_grouped_nulls or \
test_is_narwhals_lazyframe or \
test_is_unique_expr or \
test_is_unique_expr_grouped or \
test_is_unique_w_nulls_expr or \
test_join_duplicate_column_names or \
test_join_keys_exceptions or \
test_join_not_implemented or \
test_joinasof_by or \
test_joinasof_by_exceptions or \
test_joinasof_keys_exceptions or \
test_joinasof_not_implemented or \
test_joinasof_numeric or \
test_joinasof_suffix or \
test_joinasof_time or \
test_keep or \
test_keep_after_alias or \
test_keep_anonymous or \
test_key_with_nulls or \
test_key_with_nulls_ignored or \
test_kurtosis_expr or \
test_lazy_cum_count_grouped or \
test_lazy_cum_max_grouped or \
test_lazy_cum_max_ordered_by_nulls or \
test_lazy_cum_max_ungrouped or \
test_lazy_cum_max_ungrouped_ordered_by_nulls or \
test_lazy_cum_min_grouped or \
test_lazy_cum_min_ordered_by_nulls or \
test_lazy_cum_min_ungrouped or \
test_lazy_cum_min_ungrouped_ordered_by_nulls or \
test_lazy_cum_prod_grouped or \
test_lazy_cum_sum_grouped or \
test_lazy_cum_sum_ordered_by_nulls or \
test_lazy_cum_sum_ungrouped or \
test_lazy_cum_sum_ungrouped_ordered_by_nulls or \
test_lazy_rank_expr or \
test_lazy_rank_expr_desc or \
test_left_join or \
test_left_join_multiple_column or \
test_left_join_overlapping_column or \
test_left_to_right_broadcasting or \
test_len_expr or \
test_len_no_filter or \
test_len_over_2369 or \
test_lit or \
test_lit_error or \
test_lit_operation_in_select or \
test_lit_operation_in_with_columns or \
test_lit_out_name or \
test_log_expr or \
test_logic_operators_expr or \
test_logic_operators_expr_kleene or \
test_logic_operators_expr_scalar or \
test_map or \
test_map_after_alias or \
test_map_anonymous or \
test_mapping_key_not_in_expr or \
test_matches or \
test_maxh or \
test_maxh_all or \
test_meanh or \
test_meanh_all or \
test_meanh_with_literal or \
test_median_expr or \
test_median_expr_raises_on_str or \
test_minh or \
test_minh_all or \
test_missing_columns or \
test_mode_expr_keep_all_lazy or \
test_mode_expr_keep_any or \
test_mode_group_by_multimodal or \
test_mode_group_by_multiple_cols or \
test_mode_group_by_unimodal or \
test_multi_column_expansion or \
test_multiple_conditions or \
test_n_unique or \
test_n_unique_over or \
test_namespace_from_native_object or \
test_namespace_len or \
test_nan or \
test_nan_non_float or \
test_native_namespace_frame or \
test_no_agg or \
test_no_arg_when_fail or \
test_nth or \
test_null or \
test_null_count_expr or \
test_numeric or \
test_offset_by or \
test_offset_by_dst or \
test_offset_by_invalid_interval or \
test_offset_by_tz or \
test_order_dependent_raises_in_lazy or \
test_otherwise_expression or \
test_over_anonymous_reduction or \
test_over_multiple or \
test_over_pushdown or \
test_over_quantile or \
test_over_raise_len_change or \
test_over_single or \
test_over_std_var or \
test_over_without_partition_by or \
test_package_version or \
test_parse_weight or \
test_per_group_broadcasting or \
test_pipe or \
test_pipe_expr or \
test_prefix or \
test_prefix_anonymous or \
test_quantile_expr or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_desc or \
test_rank_with_order_by or \
test_rank_with_order_by_and_partition_by or \
test_rename or \
test_renaming_edge_case or \
test_replace_strict_expr_basic or \
test_replace_strict_expr_with_default or \
test_replace_strict_non_full or \
test_replace_strict_with_default_and_nulls or \
test_replace_strict_with_default_mapping or \
test_replace_strict_with_expressified_default or \
test_replace_time_zone or \
test_replace_time_zone_none or \
test_right_arithmetic_expr or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_round or \
test_scalar_reduction_select or \
test_scalar_reduction_with_columns or \
test_schema or \
test_select or \
test_select_duplicates or \
test_select_with_columns_empty_lazy or \
test_selectors or \
test_semi_join or \
test_set_ops or \
test_set_ops_invalid or \
test_shift_lazy or \
test_shift_lazy_grouped or \
test_skew_expr or \
test_sort or \
test_sort_nulls or \
test_split_list_get or \
test_sqrt_expr or \
test_starts_with or \
test_std or \
test_std_broadcating or \
test_str_head or \
test_str_len_chars or \
test_str_replace_all_expr_multivalue or \
test_str_replace_all_expr_scalar or \
test_str_replace_errors_expr or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_scalar or \
test_str_slice or \
test_str_split or \
test_str_strip_chars or \
test_str_tail or \
test_str_to_lowercase or \
test_str_to_titlecase_expr or \
test_str_to_uppercase or \
test_str_zfill or \
test_string or \
test_subtract_expr or \
test_suffix or \
test_suffix_after_alias or \
test_suffix_anonymous or \
test_sumh or \
test_sumh_aggregations or \
test_sumh_all or \
test_sumh_broadcasting or \
test_sumh_nullable or \
test_sumh_transformations or \
test_timestamp_dates or \
test_timestamp_datetimes or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_invalid_date or \
test_timestamp_invalid_unit_expr or \
test_to_date or \
test_to_date_infer_fmt_expr or \
test_to_date_with_fmt_expr or \
test_to_datetime or \
test_to_datetime_infer_fmt or \
test_to_datetime_infer_fmt_from_date or \
test_to_datetime_tz_aware or \
test_to_lowercase or \
test_to_lowercase_after_alias or \
test_to_lowercase_raise_anonymous or \
test_to_native or \
test_to_uppercase or \
test_to_uppercase_after_alias or \
test_to_uppercase_anonymous or \
test_top_k or \
test_top_k_by_multiple or \
test_top_level_len or \
test_truncate or \
test_truncate_invalid_interval or \
test_truncate_invalid_multiple or \
test_truncate_multiples or \
test_tz_aware or \
test_unary or \
test_unary_one_element or \
test_unary_two_elements or \
test_unique or \
test_unique_3069 or \
test_unique_expr or \
test_unique_expr_agg or \
test_unique_first_last or \
test_unique_first_last_no_subset or \
test_unique_full_subset or \
test_unique_illegal_combination or \
test_unique_invalid or \
test_unique_invalid_keep or \
test_unique_none or \
test_unpivot or \
test_unpivot_default_var_value_names or \
test_unpivot_mixed_types or \
test_unpivot_var_value_names or \
test_value_expression or \
test_var or \
test_when or \
test_when_otherwise or \
test_when_then_broadcasting or \
test_when_then_empty or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_both_lit or \
test_when_then_otherwise_into_expr or \
test_when_then_otherwise_lit_str or \
test_when_then_otherwise_multi_output or \
test_with_columns_dtypes_single_row or \
test_with_columns_missing_column or \
test_with_columns_order or \
test_with_columns_order_single_row or \
test_with_row_index or \
test_with_row_index_lazy or \
test_with_row_index_lazy_exception or \
test_with_row_index_lazy_meaner_examples or \
test_with_version \
"

pytest narwhals/tests \
  -p pytest_constructor_override \
  -p env \
  --use-external-constructor \
  --constructors daft \
  -k "not ( \
      ${TESTS_THAT_NEED_FIX} \
  )" \
  "$@"
