#!/bin/bash

TESTS_THAT_NEED_FIX=" \
<<<<<<< HEAD
ERROR at setup of test_schema_from_pandas_like or  \
ERROR at setup of test_schema_from_pandas_like_pyarrow or  \
test_add[daft] or  \
test_all_ignore_nulls[daft] or  \
test_all_kind_of_aggs[daft] or  \
test_allh[daft] or  \
test_allh_all[daft] or  \
test_allh_iterator[daft] or  \
test_allh_nth[daft] or  \
test_any_all[daft] or  \
test_anyh[daft] or  \
test_anyh_ignore_nulls[daft] or  \
test_arithmetic_expr[daft-__pow__-2-expected7] or  \
test_arithmetic_expr_left_literal[daft-__pow__-lhs7-expected7] or  \
test_boolean[daft] or  \
test_cast[daft] or  \
test_cast_binary[daft] or  \
test_cast_datetime_tz_aware[daft] or  \
test_cast_datetime_utc[daft] or  \
test_cast_raises_for_unknown_dtype[daft] or  \
test_cast_time[daft] or  \
test_cast_to_enum_v1[daft] or  \
test_cast_to_enum_vmain[daft] or  \
test_categorical[daft] or  \
test_ceil_expr[daft] or  \
test_clip_expr[daft--2-0-expected3] or  \
test_clip_expr[daft--2-None-expected4] or  \
test_clip_expr[daft-0-4-expected1] or  \
test_clip_expr[daft-3-4-expected0] or  \
test_clip_expr[daft-None-4-expected2] or  \
test_clip_expr_expressified[daft] or  \
test_coalesce_multi_output[daft] or  \
test_coalesce_numeric[daft] or  \
test_coalesce_strings[daft] or  \
test_collect_empty[daft] or  \
test_collect_with_kwargs[daft] or  \
test_concat_str[daft-False-expected1] or  \
test_concat_str[daft-True-expected0] or  \
test_concat_str_with_lit[daft] or  \
test_concat_vertical[daft] or  \
test_contains_case_insensitive[daft] or  \
test_contains_case_sensitive[daft] or  \
test_contains_expr[daft] or  \
test_contains_literal[daft] or  \
test_convert_time_zone[daft] or  \
test_convert_time_zone_from_none[daft] or  \
test_datetime[daft] or  \
test_datetime_attributes[daft-date-expected0] or  \
test_datetime_attributes[daft-day-expected3] or  \
test_datetime_attributes[daft-hour-expected4] or  \
test_datetime_attributes[daft-microsecond-expected8] or  \
test_datetime_attributes[daft-millisecond-expected7] or  \
test_datetime_attributes[daft-minute-expected5] or  \
test_datetime_attributes[daft-month-expected2] or  \
test_datetime_attributes[daft-nanosecond-expected9] or  \
test_datetime_attributes[daft-ordinal_day-expected10] or  \
test_datetime_attributes[daft-second-expected6] or  \
test_datetime_attributes[daft-weekday-expected11] or  \
test_datetime_attributes[daft-year-expected1] or  \
test_datetime_no_tz[daft] or  \
test_diff_lazy[daft] or  \
test_diff_lazy_grouped[daft] or  \
test_double_same_aggregation[daft] or  \
test_drop_nulls_agg[daft] or  \
test_dt_to_string_expr[daft-%G-W%V-%u] or  \
test_dt_to_string_expr[daft-%G-W%V] or  \
test_dt_to_string_expr[daft-%Y-%m-%d or  \
test_dt_to_string_expr[daft-%Y-%m-%d %H:%M:%S] or  \
test_dt_to_string_expr[daft-%Y-%m-%d] or  \
test_dt_to_string_expr[daft-%Y/%m/%d or  \
test_dt_to_string_expr[daft-%Y/%m/%d %H:%M:%S] or  \
test_dt_to_string_iso_local_date_expr[daft-data0-2020-01-09] or  \
test_dt_to_string_iso_local_datetime_expr[daft-data0-2020-01-09T12:34:56.000000] or  \
test_dt_to_string_iso_local_datetime_expr[daft-data1-2020-01-09T12:34:56.000123] or  \
test_dt_to_string_iso_local_datetime_expr[daft-data2-2020-01-09T12:34:56.123456] or  \
test_duration_attributes[daft-total_microseconds-expected_a3-expected_b3-expected_c3] or  \
test_duration_attributes[daft-total_milliseconds-expected_a2-expected_b2-expected_c2] or  \
test_duration_attributes[daft-total_minutes-expected_a0-expected_b0-expected_c0] or  \
test_duration_attributes[daft-total_nanoseconds-expected_a4-expected_b4-expected_c4] or  \
test_duration_attributes[daft-total_seconds-expected_a1-expected_b1-expected_c1] or  \
test_empty_scalar_reduction_select[daft] or  \
test_empty_scalar_reduction_with_columns[daft] or  \
test_ends_with[daft] or  \
test_exp_expr[daft] or  \
test_explode_invalid_operation_error[daft] or  \
test_explode_multiple_cols[daft-l1-more_columns0-expected0] or  \
test_explode_multiple_cols[daft-l3-more_columns1-expected1] or  \
test_explode_shape_error[daft] or  \
test_explode_single_col[daft-l2-expected_values0] or  \
test_explode_single_col[daft-l3-expected_values1] or  \
test_expr_binary[daft] or  \
test_expr_floordiv_by_zero[daft-0] or  \
test_expr_floordiv_by_zero[daft-denominator1] or  \
test_expr_floordiv_by_zero[daft-denominator2] or  \
test_expr_rfloordiv_by_zero[daft--2] or  \
test_expr_rfloordiv_by_zero[daft-2] or  \
test_expr_rtruediv_by_zero[daft--2--inf] or  \
test_expr_rtruediv_by_zero[daft--2.1--inf] or  \
test_expr_rtruediv_by_zero[daft-0-nan] or  \
test_expr_rtruediv_by_zero[daft-0.0-nan] or  \
test_expr_rtruediv_by_zero[daft-2-inf] or  \
test_expr_rtruediv_by_zero[daft-2.1-inf] or  \
test_expr_sum_expr[daft-expr0] or  \
test_expr_sum_expr[daft-expr1] or  \
test_fancy_functions[daft] or  \
test_fill_nan[daft] or  \
test_fill_null_limits[daft] or  \
test_fill_null_strategies_with_limit_as_none[daft] or  \
test_fill_null_strategies_with_partition_by[daft] or  \
test_filter[daft] or  \
test_filter_missing_column[daft] or  \
test_first_expr_over_order_by[daft] or  \
test_first_expr_over_order_by_partition_by[daft] or  \
test_floor_expr[daft] or  \
test_format[daft] or  \
test_get_expr[daft-0-expected0] or  \
test_get_field_expr[daft] or  \
test_group_by_categorical[daft] or  \
test_group_by_depth_1_agg[daft-count-expected8] or  \
test_group_by_depth_1_agg[daft-len-expected6] or  \
test_group_by_depth_1_agg[daft-max-expected2] or  \
test_group_by_depth_1_agg[daft-mean-expected1] or  \
test_group_by_depth_1_agg[daft-min-expected3] or  \
test_group_by_depth_1_agg[daft-n_unique-expected7] or  \
test_group_by_depth_1_agg[daft-std-expected4] or  \
test_group_by_depth_1_agg[daft-sum-expected0] or  \
test_group_by_depth_1_agg[daft-var-expected5] or  \
test_group_by_depth_1_agg_bool_ops[daft-not-nullable] or  \
test_group_by_depth_1_agg_bool_ops[daft-nullable] or  \
test_group_by_depth_1_std_var[daft-std-0] or  \
test_group_by_depth_1_std_var[daft-std-2] or  \
test_group_by_depth_1_std_var[daft-var-0] or  \
test_group_by_depth_1_std_var[daft-var-2] or  \
test_group_by_expr[daft-keys0-aggs0-expected0-sort_by0] or  \
test_group_by_expr[daft-keys1-aggs1-expected1-sort_by1] or  \
test_group_by_expr[daft-keys2-aggs2-expected2-sort_by2] or  \
test_group_by_expr[daft-keys3-aggs3-expected3-sort_by3] or  \
test_group_by_expr[daft-keys4-aggs4-expected4-sort_by4] or  \
test_group_by_expr[daft-keys5-aggs5-expected5-sort_by5] or  \
test_group_by_len_1_column[daft] or  \
test_group_by_median[daft] or  \
test_group_by_multiple_keys[daft] or  \
test_group_by_n_unique_w_missing[daft] or  \
test_group_by_nw_all[daft] or  \
test_group_by_selector[daft] or  \
test_group_by_shift_raises[daft] or  \
test_group_by_simple_named[daft] or  \
test_group_by_simple_unnamed[daft] or  \
test_group_by_window[daft] or  \
test_invalid_operations[daft-expr17] or  \
test_is_close_expr_with_expr[daft-0.0-0.001-True-expected3] or  \
test_is_close_expr_with_expr[daft-0.0-0.1-False-expected2] or  \
test_is_close_expr_with_expr[daft-0.0001-0.0-True-expected1] or  \
test_is_close_expr_with_expr[daft-0.1-0.0-False-expected0] or  \
test_is_close_expr_with_scalar[daft-1.0-0.0001-0.0-True-expected1] or  \
test_is_close_expr_with_scalar[daft-1.0-0.1-0.0-False-expected0] or  \
test_is_close_expr_with_scalar[daft-2.9-0.0-0.001-True-expected3] or  \
test_is_close_expr_with_scalar[daft-2.9-0.0-0.1-False-expected2] or  \
test_is_duplicated_expr[daft] or  \
test_is_duplicated_w_nulls_expr[daft] or  \
test_is_finite_expr[daft] or  \
test_is_first_distinct_expr_lazy[daft] or  \
test_is_first_distinct_expr_lazy_grouped[daft] or  \
test_is_last_distinct_expr_lazy[daft] or  \
test_is_last_distinct_expr_lazy_grouped[daft] or  \
test_is_last_distinct_expr_lazy_grouped_nulls[daft] or  \
test_is_unique_expr[daft] or  \
test_is_unique_expr_grouped[daft] or  \
test_is_unique_w_nulls_expr[daft] or  \
test_joinasof_by[daft] or  \
test_joinasof_numeric[daft-backward-expected0] or  \
test_joinasof_numeric[daft-forward-expected1] or  \
test_joinasof_numeric[daft-nearest-expected2] or  \
test_joinasof_suffix[daft] or  \
test_joinasof_time[daft-backward-expected0] or  \
test_joinasof_time[daft-forward-expected1] or  \
test_joinasof_time[daft-nearest-expected2] or  \
test_key_with_nulls[daft] or  \
test_key_with_nulls_ignored[daft] or  \
test_kurtosis_expr[daft-0] or  \
test_kurtosis_expr[daft-1] or  \
test_kurtosis_expr[daft-2] or  \
test_kurtosis_expr[daft-3] or  \
test_kurtosis_expr[daft-4] or  \
test_lazy_cum_count_grouped[daft-False-expected_a0] or  \
test_lazy_cum_count_grouped[daft-True-expected_a1] or  \
test_lazy_cum_max_grouped[daft-False-expected_a0] or  \
test_lazy_cum_max_grouped[daft-True-expected_a1] or  \
test_lazy_cum_max_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_max_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_cum_max_ungrouped[daft-False-expected_a0] or  \
test_lazy_cum_max_ungrouped[daft-True-expected_a1] or  \
test_lazy_cum_max_ungrouped_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_max_ungrouped_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_cum_min_grouped[daft-False-expected_a0] or  \
test_lazy_cum_min_grouped[daft-True-expected_a1] or  \
test_lazy_cum_min_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_min_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_cum_min_ungrouped[daft-False-expected_a0] or  \
test_lazy_cum_min_ungrouped[daft-True-expected_a1] or  \
test_lazy_cum_min_ungrouped_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_min_ungrouped_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_cum_prod_grouped[daft-False-expected_a0] or  \
test_lazy_cum_prod_grouped[daft-True-expected_a1] or  \
test_lazy_cum_sum_grouped[daft-False-expected_a0] or  \
test_lazy_cum_sum_grouped[daft-True-expected_a1] or  \
test_lazy_cum_sum_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_sum_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_cum_sum_ungrouped[daft-False-expected_a0] or  \
test_lazy_cum_sum_ungrouped[daft-True-expected_a1] or  \
test_lazy_cum_sum_ungrouped_ordered_by_nulls[daft-False-expected_a0] or  \
test_lazy_cum_sum_ungrouped_ordered_by_nulls[daft-True-expected_a1] or  \
test_lazy_rank_expr[daft-data0-average] or  \
test_lazy_rank_expr[daft-data0-dense] or  \
test_lazy_rank_expr[daft-data0-max] or  \
test_lazy_rank_expr[daft-data0-min] or  \
test_lazy_rank_expr[daft-data0-ordinal] or  \
test_lazy_rank_expr[daft-data1-average] or  \
test_lazy_rank_expr[daft-data1-dense] or  \
test_lazy_rank_expr[daft-data1-max] or  \
test_lazy_rank_expr[daft-data1-min] or  \
test_lazy_rank_expr[daft-data1-ordinal] or  \
test_lazy_rank_expr_desc[daft-data0-average] or  \
test_lazy_rank_expr_desc[daft-data0-dense] or  \
test_lazy_rank_expr_desc[daft-data0-max] or  \
test_lazy_rank_expr_desc[daft-data0-min] or  \
test_lazy_rank_expr_desc[daft-data0-ordinal] or  \
test_lazy_rank_expr_desc[daft-data1-average] or  \
test_lazy_rank_expr_desc[daft-data1-dense] or  \
test_lazy_rank_expr_desc[daft-data1-max] or  \
test_lazy_rank_expr_desc[daft-data1-min] or  \
test_lazy_rank_expr_desc[daft-data1-ordinal] or  \
test_left_to_right_broadcasting[daft] or  \
test_len_expr[daft] or  \
test_lit[daft-Float32-expected_lit2] or  \
test_lit[daft-None-expected_lit0] or  \
test_lit[daft-String-expected_lit1] or  \
test_lit_operation_in_select[daft-right_lit_with_abs-expr2-expected_result2] or  \
test_lit_operation_in_with_columns[daft-lit_and_scalar-expr0-expected_result0] or  \
test_lit_operation_in_with_columns[daft-scalar_and_lit-expr1-expected_result1] or  \
test_map_after_alias[daft] or  \
test_matches[daft] or  \
test_maxh[daft] or  \
test_maxh_all[daft] or  \
test_meanh[daft] or  \
test_meanh_all[daft] or  \
test_meanh_with_literal[daft] or  \
test_median_expr[daft-expr0] or  \
test_median_expr[daft-expr1] or  \
test_median_expr_raises_on_str[daft-expr0] or  \
test_median_expr_raises_on_str[daft-expr1] or  \
test_minh[daft] or  \
test_minh_all[daft] or  \
test_missing_columns[daft] or  \
test_mode_expr_keep_all_lazy[daft] or  \
test_mode_expr_keep_any[daft] or  \
test_mode_group_by_multimodal[daft-vals_multimodal_num-expected_opt_10-expected_opt_20] or  \
test_mode_group_by_multimodal[daft-vals_multimodal_str-expected_opt_11-expected_opt_21] or  \
test_mode_group_by_multiple_cols[daft-mode_expr0] or  \
test_mode_group_by_multiple_cols[daft-mode_expr1] or  \
test_mode_group_by_unimodal[daft] or  \
test_multi_column_expansion[daft] or  \
test_multiple_conditions[daft] or  \
test_n_unique_over[daft] or  \
test_namespace_from_native_object[daft] or  \
test_nan[daft] or  \
test_nan_non_float[daft] or  \
test_native_namespace_frame[daft] or  \
test_no_agg[daft] or  \
test_numeric[daft] or  \
test_offset_by[daft--13d-expected13] or  \
test_offset_by[daft--2000ns-expected11] or  \
test_offset_by[daft--2us-expected10] or  \
test_offset_by[daft--3y-expected14] or  \
test_offset_by[daft--7h-expected12] or  \
test_offset_by[daft-10s-expected3] or  \
test_offset_by[daft-13d-expected6] or  \
test_offset_by[daft-2000ns-expected1] or  \
test_offset_by[daft-2ms-expected2] or  \
test_offset_by[daft-2q-expected8] or  \
test_offset_by[daft-2us-expected0] or  \
test_offset_by[daft-3mo-expected7] or  \
test_offset_by[daft-3y-expected9] or  \
test_offset_by[daft-7h-expected5] or  \
test_offset_by[daft-7m-expected4] or  \
test_offset_by_dst[daft-1q-2021-01-25T02:00+0100] or  \
test_offset_by_dst[daft-2d-2020-10-27T02:00+0100] or  \
test_offset_by_dst[daft-5mo-2021-03-25T02:00+0100] or  \
test_offset_by_invalid_interval[daft] or  \
test_offset_by_tz[daft-2d-2024-01-03T05:45+0545] or  \
test_offset_by_tz[daft-5mo-2024-06-01T05:45+0545] or  \
test_offset_by_tz[daft-5y-2029-01-01T05:45+0545] or  \
test_offset_by_tz[daft-7q-2025-10-01T05:45+0545] or  \
test_order_dependent_raises_in_lazy[daft] or  \
test_otherwise_expression[daft] or  \
test_over_anonymous_reduction[daft] or  \
test_over_pushdown[daft-expr10-expected10] or  \
test_over_pushdown[daft-expr11-expected11] or  \
test_over_pushdown[daft-expr12-expected12] or  \
test_over_pushdown[daft-expr2-expected2] or  \
test_over_pushdown[daft-expr3-expected3] or  \
test_over_pushdown[daft-expr4-expected4] or  \
test_over_pushdown[daft-expr5-expected5] or  \
test_over_pushdown[daft-expr6-expected6] or  \
test_over_pushdown[daft-expr7-expected7] or  \
test_over_pushdown[daft-expr8-expected8] or  \
test_over_pushdown[daft-expr9-expected9] or  \
test_over_pushdown[daft] or  \
test_over_quantile[daft] or  \
test_over_std_var[daft] or  \
test_over_without_partition_by[daft] or  \
test_package_version or  \
test_pandas_datetime_ignored_time_unit_warns[Datetime-context1] or  \
test_pandas_datetime_ignored_time_unit_warns[dtype0-context0] or  \
test_pandas_datetime_ignored_time_unit_warns[dtype2-context2] or  \
test_pandas_datetime_ignored_time_unit_warns[dtype3-context3] or  \
test_pandas_datetime_ignored_time_unit_warns[dtype4-context4] or  \
test_parse_weight[daft] or  \
test_pipe_expr[daft] or  \
test_q1[pandas] or  \
test_q1[polars] or  \
test_q1[pyarrow] or  \
test_q1_w_generic_funcs[pandas] or  \
test_q1_w_generic_funcs[polars] or  \
test_q1_w_pandas_agg_generic_path or  \
test_quantile_expr[daft-higher-expected1] or  \
test_quantile_expr[daft-linear-expected3] or  \
test_quantile_expr[daft-lower-expected0] or  \
test_quantile_expr[daft-midpoint-expected2] or  \
test_quantile_expr[daft-nearest-expected4] or  \
test_rank_expr_in_over_context[daft-average] or  \
test_rank_expr_in_over_context[daft-dense] or  \
test_rank_expr_in_over_context[daft-max] or  \
test_rank_expr_in_over_context[daft-min] or  \
test_rank_expr_in_over_context[daft-ordinal] or  \
test_rank_expr_in_over_desc[daft-average] or  \
test_rank_expr_in_over_desc[daft-dense] or  \
test_rank_expr_in_over_desc[daft-max] or  \
test_rank_expr_in_over_desc[daft-min] or  \
test_rank_expr_in_over_desc[daft-ordinal] or  \
test_rank_with_order_by[daft] or  \
test_rank_with_order_by_and_partition_by[daft] or  \
test_renaming_edge_case[daft] or  \
test_replace_strict_expr_basic[daft-old0-new0-return_dtype0] or  \
test_replace_strict_expr_basic[daft-old1-new1-None] or  \
test_replace_strict_expr_basic[daft-old2-None-return_dtype2] or  \
test_replace_strict_expr_with_default[daft-None] or  \
test_replace_strict_expr_with_default[daft-return_dtype0] or  \
test_replace_strict_non_full[daft] or  \
test_replace_strict_with_default_and_nulls[daft] or  \
test_replace_strict_with_default_mapping[daft] or  \
test_replace_strict_with_expressified_default[daft] or  \
test_replace_time_zone[daft] or  \
test_replace_time_zone_none[daft] or  \
test_right_arithmetic_expr[daft-__rmod__-2-expected5] or  \
test_right_arithmetic_expr[daft-__rpow__-2-expected6] or  \
test_right_arithmetic_expr[daft-__rsub__-1-expected1] or  \
test_right_arithmetic_expr[daft-__rtruediv__-2.0-expected3] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a0-2-None-False] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a1-2-2-False] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a2-3-2-False] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a3-3-1-False] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a4-3-1-True] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a5-4-1-True] or  \
test_rolling_mean_expr_lazy_grouped[daft-expected_a6-5-1-True] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a0-2-None-False] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a1-2-2-False] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a2-3-2-False] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a3-3-1-False] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a4-3-1-True] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a5-4-1-True] or  \
test_rolling_mean_expr_lazy_ungrouped[daft-expected_a6-5-1-True] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a0-2-None-False-0] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a1-2-2-False-1] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a2-3-2-False-1] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a3-3-1-False-0] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a4-3-1-True-1] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a5-4-1-True-1] or  \
test_rolling_std_expr_lazy_grouped[daft-expected_a6-5-1-True-0] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a0-2-None-False-0] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a1-2-2-False-1] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a2-3-2-False-1] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a3-3-1-False-0] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a4-3-1-True-1] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a5-4-1-True-1] or  \
test_rolling_std_expr_lazy_ungrouped[daft-expected_a6-5-1-True-0] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a0-2-None-False] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a1-2-2-False] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a2-3-2-False] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a3-3-1-False] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a4-3-1-True] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a5-4-1-True] or  \
test_rolling_sum_expr_lazy_grouped[daft-expected_a6-5-1-True] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a0-2-None-False] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a1-2-2-False] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a2-3-2-False] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a3-3-1-False] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a4-3-1-True] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a5-4-1-True] or  \
test_rolling_sum_expr_lazy_ungrouped[daft-expected_a6-5-1-True] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a0-2-None-False-0] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a1-2-2-False-1] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a2-3-2-False-1] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a3-3-1-False-0] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a4-3-1-True-1] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a5-4-1-True-1] or  \
test_rolling_var_expr_lazy_grouped[daft-expected_a6-5-1-True-0] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a0-2-None-False-0] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a1-2-2-False-1] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a2-3-2-False-1] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a3-3-1-False-0] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a4-3-1-True-1] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a5-4-1-True-1] or  \
test_rolling_var_expr_lazy_ungrouped[daft-expected_a6-5-1-True-0] or  \
test_scan_csv[daft-PathLike] or  \
test_scan_csv[daft-Path] or  \
test_scan_csv[daft-str] or  \
test_scan_parquet[daft-PathLike] or  \
test_scan_parquet[daft-Path] or  \
test_scan_parquet[daft-str] or  \
test_schema_from_pandas_like or  \
test_schema_from_pandas_like_pyarrow or  \
test_select_duplicates[daft] or  \
test_selectors[daft] or  \
test_set_ops[daft-selector0-expected0] or  \
test_set_ops[daft-selector1-expected1] or  \
test_set_ops[daft-selector2-expected2] or  \
test_set_ops[daft-selector3-expected3] or  \
test_set_ops[daft-selector4-expected4] or  \
test_set_ops[daft-selector5-expected5] or  \
test_set_ops[daft-selector6-expected6] or  \
test_set_ops[daft-selector7-expected7] or  \
test_set_ops[daft-selector8-expected8] or  \
test_shift_lazy[daft] or  \
test_shift_lazy_grouped[daft] or  \
test_sink_parquet[daft] or  \
test_skew_expr[daft-0] or  \
test_split_list_get[daft] or  \
test_sqrt_expr[daft] or  \
test_starts_with[daft] or  \
test_std_broadcating[daft] or  \
test_str_head[daft] or  \
test_str_len_chars[daft] or  \
test_str_replace_all_expr_multivalue[daft-data0-abc-b-False-expected0] or  \
test_str_replace_all_expr_multivalue[daft-data1-abc-b-False-expected1] or  \
test_str_replace_all_expr_multivalue[daft-data2-$-b-True-expected2] or  \
test_str_replace_all_expr_scalar[daft-data0-abc\\b-ABC-False-expected0] or  \
test_str_replace_all_expr_scalar[daft-data1-abc--False-expected1] or  \
test_str_replace_all_expr_scalar[daft-data2-abc--False-expected2] or  \
test_str_replace_all_expr_scalar[daft-data3-$-S-True-expected3] or  \
test_str_replace_errors_expr[daft] or  \
test_str_replace_expr_multivalue[daft-data0-abc-b-1-False-expected0] or  \
test_str_replace_expr_multivalue[daft-data1-abc-b-1-False-expected1] or  \
test_str_replace_expr_multivalue[daft-data2-abc-b--1-False-expected2] or  \
test_str_replace_expr_multivalue[daft-data3-$-b--1-True-expected3] or  \
test_str_replace_expr_scalar[daft-data0-abc\\b-ABC-1-False-expected0] or  \
test_str_replace_expr_scalar[daft-data1-abc--1-False-expected1] or  \
test_str_replace_expr_scalar[daft-data2-abc---1-False-expected2] or  \
test_str_replace_expr_scalar[daft-data3-$-S--1-True-expected3] or  \
test_str_slice[daft--2-None-expected1] or  \
test_str_slice[daft-1-2-expected0] or  \
test_str_split[daft-,-expected1] or  \
test_str_split[daft-_-expected0] or  \
test_str_strip_chars[daft-None-expected0] or  \
test_str_strip_chars[daft-foo-expected1] or  \
test_str_tail[daft] or  \
test_str_to_lowercase[daft-data0-expected0] or  \
test_str_to_lowercase[daft-data1-expected1] or  \
test_str_to_titlecase_expr[daft] or  \
test_str_to_uppercase[daft-data0-expected0] or  \
test_str_zfill[daft] or  \
test_string[daft] or  \
test_subtract_expr[daft] or  \
test_suffix_after_alias[daft] or  \
test_sumh[daft] or  \
test_sumh_aggregations[daft] or  \
test_sumh_all[daft] or  \
test_sumh_broadcasting[daft] or  \
test_sumh_nullable[daft] or  \
test_sumh_transformations[daft] or  \
test_timestamp_dates[daft-ms-expected2] or  \
test_timestamp_dates[daft-ns-expected0] or  \
test_timestamp_dates[daft-us-expected1] or  \
test_timestamp_datetimes[daft-ms-ms-expected8] or  \
test_timestamp_datetimes[daft-ms-ns-expected6] or  \
test_timestamp_datetimes[daft-ms-us-expected7] or  \
test_timestamp_datetimes[daft-ns-ms-expected2] or  \
test_timestamp_datetimes[daft-ns-ns-expected0] or  \
test_timestamp_datetimes[daft-ns-us-expected1] or  \
test_timestamp_datetimes[daft-s-ms-expected11] or  \
test_timestamp_datetimes[daft-s-ns-expected9] or  \
test_timestamp_datetimes[daft-s-us-expected10] or  \
test_timestamp_datetimes[daft-us-ms-expected5] or  \
test_timestamp_datetimes[daft-us-ns-expected3] or  \
test_timestamp_datetimes[daft-us-us-expected4] or  \
test_timestamp_datetimes_tz_aware[daft-ms-ms-expected8] or  \
test_timestamp_datetimes_tz_aware[daft-ms-ns-expected6] or  \
test_timestamp_datetimes_tz_aware[daft-ms-us-expected7] or  \
test_timestamp_datetimes_tz_aware[daft-ns-ms-expected2] or  \
test_timestamp_datetimes_tz_aware[daft-ns-ns-expected0] or  \
test_timestamp_datetimes_tz_aware[daft-ns-us-expected1] or  \
test_timestamp_datetimes_tz_aware[daft-s-ms-expected11] or  \
test_timestamp_datetimes_tz_aware[daft-s-ns-expected9] or  \
test_timestamp_datetimes_tz_aware[daft-s-us-expected10] or  \
test_timestamp_datetimes_tz_aware[daft-us-ms-expected5] or  \
test_timestamp_datetimes_tz_aware[daft-us-ns-expected3] or  \
test_timestamp_datetimes_tz_aware[daft-us-us-expected4] or  \
test_timestamp_invalid_date[daft] or  \
test_to_date[daft] or  \
test_to_date_infer_fmt_expr[daft] or  \
test_to_date_with_fmt_expr[daft] or  \
test_to_datetime[daft] or  \
test_to_datetime_infer_fmt[daft-data0-2020-01-01 or  \
test_to_datetime_infer_fmt[daft-data1-2020-01-01 or  \
test_to_datetime_infer_fmt[daft-data2-2024-01-01 or  \
test_to_datetime_infer_fmt_from_date[daft] or  \
test_to_datetime_tz_aware[daft-%Y-%m-%dT%H:%M:%S%z] or  \
test_to_datetime_tz_aware[daft-None] or  \
test_to_lowercase_after_alias[daft] or  \
test_to_uppercase_after_alias[daft] or  \
test_top_k[daft] or  \
test_top_k_by_multiple[daft] or  \
test_top_level_len[daft] or  \
test_truncate[daft-1d-expected6] or  \
test_truncate[daft-1h-expected5] or  \
test_truncate[daft-1m-expected4] or  \
test_truncate[daft-1mo-expected7] or  \
test_truncate[daft-1ms-expected2] or  \
test_truncate[daft-1ns-expected0] or  \
test_truncate[daft-1q-expected8] or  \
test_truncate[daft-1s-expected3] or  \
test_truncate[daft-1us-expected1] or  \
test_truncate[daft-1y-expected9] or  \
test_truncate_invalid_interval[daft] or  \
test_truncate_invalid_multiple[daft] or  \
test_truncate_multiples[daft-10s-expected3] or  \
test_truncate_multiples[daft-13d-expected6] or  \
test_truncate_multiples[daft-2ms-expected2] or  \
test_truncate_multiples[daft-2ns-expected0] or  \
test_truncate_multiples[daft-2q-expected8] or  \
test_truncate_multiples[daft-2us-expected1] or  \
test_truncate_multiples[daft-3mo-expected7] or  \
test_truncate_multiples[daft-7h-expected5] or  \
test_truncate_multiples[daft-7m-expected4] or  \
test_tz_aware[daft] or  \
test_unary[daft] or  \
test_unique[daft-any-expected0] or  \
test_unique[daft-none-expected1] or  \
test_unique_3069[daft] or  \
test_unique_expr[daft] or  \
test_unique_expr_agg[daft] or  \
test_unique_first_last[daft-first-expected0] or  \
test_unique_first_last[daft-last-expected1] or  \
test_unique_first_last_no_subset[daft-first-expected0] or  \
test_unique_first_last_no_subset[daft-last-expected1] or  \
test_unique_full_subset[daft-any-expected0-None] or  \
test_unique_full_subset[daft-any-expected0-subset1] or  \
test_unique_full_subset[daft-none-expected1-None] or  \
test_unique_full_subset[daft-none-expected1-subset1] or  \
test_unique_invalid[daft] or  \
test_unique_none[daft] or  \
test_value_expression[daft] or  \
test_when[daft] or  \
test_when_otherwise[daft] or  \
test_when_then_broadcasting[daft] or  \
test_when_then_empty[daft] or  \
test_when_then_otherwise_aggregate_select[daft-condition0-100-None-expected0] or  \
test_when_then_otherwise_aggregate_select[daft-condition1-100-200-expected1] or  \
test_when_then_otherwise_aggregate_select[daft-condition2-then2-200-expected2] or  \
test_when_then_otherwise_aggregate_select[daft-condition3-100-otherwise3-expected3] or  \
test_when_then_otherwise_aggregate_select[daft-condition4-then4-otherwise4-expected4] or  \
test_when_then_otherwise_aggregate_select[daft-condition5-100-None-expected5] or  \
test_when_then_otherwise_aggregate_select[daft-condition6-100-200-expected6] or  \
test_when_then_otherwise_aggregate_select[daft-condition7-then7-200-expected7] or  \
test_when_then_otherwise_aggregate_select[daft-condition8-100-otherwise8-expected8] or  \
test_when_then_otherwise_aggregate_select[daft-condition9-then9-otherwise9-expected9] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition0-100-None-expected0] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition1-100-200-expected1] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition2-then2-200-expected2] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition3-100-otherwise3-expected3] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition4-then4-otherwise4-expected4] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition5-100-None-expected5] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition6-100-200-expected6] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition7-then7-200-expected7] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition8-100-otherwise8-expected8] or  \
test_when_then_otherwise_aggregate_with_columns[daft-condition9-then9-otherwise9-expected9] or  \
test_when_then_otherwise_both_lit[daft] or  \
test_when_then_otherwise_into_expr[daft] or  \
test_when_then_otherwise_lit_str[daft] or  \
test_when_then_otherwise_multi_output[daft] or  \
test_with_columns_dtypes_single_row[daft] or  \
test_with_columns_missing_column[daft] or  \
=======
test_add or \
test_all_ignore_nulls or \
test_all_kind_of_aggs or \
test_allh or \
test_allh_all or \
test_allh_iterator or \
test_allh_nth or \
test_anti_join or \
test_anti_join or \
test_anti_join or \
test_any_all or \
test_anyh or \
test_anyh_ignore_nulls or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_arithmetic_expr_left_literal or \
test_boolean or \
test_cast or \
test_cast_binary or \
test_cast_datetime_tz_aware or \
test_cast_datetime_utc or \
test_cast_raises_for_unknown_dtype or \
test_cast_time or \
test_cast_to_enum_v1 or \
test_cast_to_enum_vmain or \
test_categorical or \
test_ceil_expr or \
test_clip_expr or \
test_clip_expr or \
test_clip_expr or \
test_clip_expr or \
test_clip_expr or \
test_clip_expr_expressified or \
test_coalesce_multi_output or \
test_coalesce_numeric or \
test_coalesce_strings or \
test_collect_empty or \
test_collect_with_kwargs or \
test_comparand_operators_scalar_expr or \
test_comparand_operators_scalar_expr or \
test_comparand_operators_scalar_expr or \
test_comparand_operators_scalar_expr or \
test_comparand_operators_scalar_expr or \
test_comparand_operators_scalar_expr or \
test_concat_str or \
test_concat_str or \
test_concat_str_with_lit or \
test_concat_vertical or \
test_contains_case_insensitive or \
test_contains_case_sensitive or \
test_contains_expr or \
test_contains_literal or \
test_convert_time_zone or \
test_convert_time_zone_from_none or \
test_date_lit or \
test_datetime or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_attributes or \
test_datetime_no_tz or \
test_diff_lazy or \
test_diff_lazy_grouped or \
test_double or \
test_double or \
test_double_alias or \
test_double_same_aggregation or \
test_double_selected or \
test_drop_nulls_agg or \
test_dt_to_string_expr or \
test_dt_to_string_expr or \
test_dt_to_string_expr or \
test_dt_to_string_expr or \
test_dt_to_string_expr or \
test_dt_to_string_iso_local_date_expr or \
test_dt_to_string_iso_local_datetime_expr or \
test_dt_to_string_iso_local_datetime_expr or \
test_dt_to_string_iso_local_datetime_expr or \
test_duration_attributes or \
test_duration_attributes or \
test_duration_attributes or \
test_duration_attributes or \
test_duration_attributes or \
test_empty_scalar_reduction_select or \
test_empty_scalar_reduction_with_columns or \
test_ends_with or \
test_exp_expr or \
test_explode_invalid_operation_error or \
test_explode_multiple_cols or \
test_explode_multiple_cols or \
test_explode_shape_error or \
test_explode_single_col or \
test_explode_single_col or \
test_expr_binary or \
test_expr_floordiv_by_zero or \
test_expr_floordiv_by_zero or \
test_expr_floordiv_by_zero or \
test_expr_rfloordiv_by_zero or \
test_expr_rfloordiv_by_zero or \
test_expr_rfloordiv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_rtruediv_by_zero or \
test_expr_sum_expr or \
test_expr_sum_expr or \
test_expr_truediv_by_zero or \
test_expr_truediv_by_zero or \
test_fancy_functions or \
test_fill_nan or \
test_fill_null or \
test_fill_null_limits or \
test_fill_null_strategies_with_limit_as_none or \
test_fill_null_strategies_with_partition_by or \
test_fill_null_w_aggregate or \
test_filter or \
test_filter_constraints or \
test_filter_is_between or \
test_filter_missing_column or \
test_filter_multiple_predicates or \
test_filter_seq_iterable_all_false or \
test_filter_seq_iterable_all_false or \
test_filter_seq_iterable_all_true or \
test_filter_seq_iterable_all_true or \
test_filter_string_predicate or \
test_filter_with_constrains_only or \
test_filter_with_expr_predicates or \
test_filter_with_expr_predicates or \
test_first_expr_over_order_by or \
test_first_expr_over_order_by_partition_by or \
test_floor_expr or \
test_format or \
test_get_expr or \
test_get_field_expr or \
test_group_by_categorical or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg or \
test_group_by_depth_1_agg_bool_ops or \
test_group_by_depth_1_agg_bool_ops or \
test_group_by_depth_1_std_var or \
test_group_by_depth_1_std_var or \
test_group_by_depth_1_std_var or \
test_group_by_depth_1_std_var or \
test_group_by_expr or \
test_group_by_expr or \
test_group_by_expr or \
test_group_by_expr or \
test_group_by_expr or \
test_group_by_expr or \
test_group_by_len_1_column or \
test_group_by_median or \
test_group_by_multiple_keys or \
test_group_by_n_unique_w_missing or \
test_group_by_nw_all or \
test_group_by_selector or \
test_group_by_shift_raises or \
test_group_by_simple_named or \
test_group_by_simple_unnamed or \
test_group_by_window or \
test_is_between or \
test_is_between or \
test_is_between or \
test_is_between or \
test_is_between_datetimes or \
test_is_between_datetimes or \
test_is_between_datetimes or \
test_is_between_datetimes or \
test_is_between_expressified or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_expr or \
test_is_close_expr_with_scalar or \
test_is_close_expr_with_scalar or \
test_is_close_expr_with_scalar or \
test_is_close_expr_with_scalar or \
test_is_duplicated_expr or \
test_is_duplicated_w_nulls_expr or \
test_is_finite_expr or \
test_is_first_distinct_expr_lazy or \
test_is_first_distinct_expr_lazy_grouped or \
test_is_last_distinct_expr_lazy or \
test_is_last_distinct_expr_lazy_grouped or \
test_is_last_distinct_expr_lazy_grouped_nulls or \
test_is_unique_expr or \
test_is_unique_expr_grouped or \
test_is_unique_w_nulls_expr or \
test_joinasof_by or \
test_joinasof_numeric or \
test_joinasof_numeric or \
test_joinasof_numeric or \
test_joinasof_suffix or \
test_joinasof_time or \
test_joinasof_time or \
test_joinasof_time or \
test_keep or \
test_key_with_nulls or \
test_key_with_nulls_ignored or \
test_kurtosis_expr or \
test_kurtosis_expr or \
test_kurtosis_expr or \
test_kurtosis_expr or \
test_kurtosis_expr or \
test_lazy_cum_count_grouped or \
test_lazy_cum_count_grouped or \
test_lazy_cum_max_grouped or \
test_lazy_cum_max_grouped or \
test_lazy_cum_max_ordered_by_nulls or \
test_lazy_cum_max_ordered_by_nulls or \
test_lazy_cum_max_ungrouped or \
test_lazy_cum_max_ungrouped or \
test_lazy_cum_max_ungrouped_ordered_by_nulls or \
test_lazy_cum_max_ungrouped_ordered_by_nulls or \
test_lazy_cum_min_grouped or \
test_lazy_cum_min_grouped or \
test_lazy_cum_min_ordered_by_nulls or \
test_lazy_cum_min_ordered_by_nulls or \
test_lazy_cum_min_ungrouped or \
test_lazy_cum_min_ungrouped or \
test_lazy_cum_min_ungrouped_ordered_by_nulls or \
test_lazy_cum_min_ungrouped_ordered_by_nulls or \
test_lazy_cum_prod_grouped or \
test_lazy_cum_prod_grouped or \
test_lazy_cum_sum_grouped or \
test_lazy_cum_sum_grouped or \
test_lazy_cum_sum_ordered_by_nulls or \
test_lazy_cum_sum_ordered_by_nulls or \
test_lazy_cum_sum_ungrouped or \
test_lazy_cum_sum_ungrouped or \
test_lazy_cum_sum_ungrouped_ordered_by_nulls or \
test_lazy_cum_sum_ungrouped_ordered_by_nulls or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_lazy_rank_expr_desc or \
test_left_to_right_broadcasting or \
test_len_expr or \
test_len_over_2369 or \
test_lit or \
test_lit or \
test_lit or \
test_lit_operation_in_select or \
test_lit_operation_in_select or \
test_lit_operation_in_select or \
test_lit_operation_in_select or \
test_lit_operation_in_select or \
test_lit_operation_in_select or \
test_lit_operation_in_with_columns or \
test_lit_operation_in_with_columns or \
test_lit_out_name or \
test_logic_operators_expr_scalar or \
test_logic_operators_expr_scalar or \
test_logic_operators_expr_scalar or \
test_logic_operators_expr_scalar or \
test_map or \
test_map_after_alias or \
test_matches or \
test_maxh or \
test_maxh_all or \
test_meanh or \
test_meanh_all or \
test_meanh_with_literal or \
test_median_expr or \
test_median_expr or \
test_median_expr_raises_on_str or \
test_median_expr_raises_on_str or \
test_minh or \
test_minh_all or \
test_missing_columns or \
test_mode_expr_keep_all_lazy or \
test_mode_expr_keep_any or \
test_mode_group_by_multimodal or \
test_mode_group_by_multimodal or \
test_mode_group_by_multiple_cols or \
test_mode_group_by_multiple_cols or \
test_mode_group_by_unimodal or \
test_multi_column_expansion or \
test_multiple_conditions or \
test_n_unique_over or \
test_namespace_from_native_object or \
test_namespace_len or \
test_nan or \
test_nan_non_float or \
test_native_namespace_frame or \
test_no_agg or \
test_numeric or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by or \
test_offset_by_dst or \
test_offset_by_dst or \
test_offset_by_dst or \
test_offset_by_invalid_interval or \
test_offset_by_tz or \
test_offset_by_tz or \
test_offset_by_tz or \
test_offset_by_tz or \
test_order_dependent_raises_in_lazy or \
test_otherwise_expression or \
test_over_anonymous_reduction or \
test_over_multiple or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_pushdown or \
test_over_quantile or \
test_over_single or \
test_over_std_var or \
test_over_without_partition_by or \
test_package_version or \
test_pandas_datetime_ignored_time_unit_warns or \
test_pandas_datetime_ignored_time_unit_warns or \
test_pandas_datetime_ignored_time_unit_warns or \
test_pandas_datetime_ignored_time_unit_warns or \
test_pandas_datetime_ignored_time_unit_warns or \
test_parse_weight or \
test_per_group_broadcasting or \
test_pipe_expr or \
test_prefix or \
test_q1 or \
test_q1 or \
test_q1 or \
test_q1_w_generic_funcs or \
test_q1_w_generic_funcs or \
test_q1_w_pandas_agg_generic_path or \
test_quantile_expr or \
test_quantile_expr or \
test_quantile_expr or \
test_quantile_expr or \
test_quantile_expr or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_context or \
test_rank_expr_in_over_desc or \
test_rank_expr_in_over_desc or \
test_rank_expr_in_over_desc or \
test_rank_expr_in_over_desc or \
test_rank_expr_in_over_desc or \
test_rank_with_order_by or \
test_rank_with_order_by_and_partition_by or \
test_renaming_edge_case or \
test_replace_strict_expr_basic or \
test_replace_strict_expr_basic or \
test_replace_strict_expr_basic or \
test_replace_strict_expr_with_default or \
test_replace_strict_expr_with_default or \
test_replace_strict_non_full or \
test_replace_strict_with_default_and_nulls or \
test_replace_strict_with_default_mapping or \
test_replace_strict_with_expressified_default or \
test_replace_time_zone or \
test_replace_time_zone_none or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_right_arithmetic_expr or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_grouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_mean_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_grouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_std_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_grouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_sum_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_grouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_rolling_var_expr_lazy_ungrouped or \
test_scalar_reduction_select or \
test_scalar_reduction_select or \
test_scalar_reduction_select or \
test_scalar_reduction_select or \
test_scalar_reduction_with_columns or \
test_scalar_reduction_with_columns or \
test_scalar_reduction_with_columns or \
test_scalar_reduction_with_columns or \
test_scalar_reduction_with_columns or \
test_scan_csv or \
test_scan_csv or \
test_scan_csv or \
test_scan_parquet or \
test_scan_parquet or \
test_scan_parquet or \
test_schema_from_pandas_like or \
test_schema_from_pandas_like_pyarrow or \
test_select_duplicates or \
test_selectors or \
test_semi_join or \
test_semi_join or \
test_semi_join or \
test_semi_join or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_set_ops or \
test_shift_lazy or \
test_shift_lazy_grouped or \
test_sink_parquet or \
test_skew_expr or \
test_skew_expr or \
test_skew_expr or \
test_skew_expr or \
test_skew_expr or \
test_split_list_get or \
test_sqrt_expr or \
test_starts_with or \
test_std_broadcating or \
test_str_head or \
test_str_len_chars or \
test_str_replace_all_expr_multivalue or \
test_str_replace_all_expr_multivalue or \
test_str_replace_all_expr_multivalue or \
test_str_replace_all_expr_scalar or \
test_str_replace_all_expr_scalar or \
test_str_replace_all_expr_scalar or \
test_str_replace_all_expr_scalar or \
test_str_replace_errors_expr or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_multivalue or \
test_str_replace_expr_scalar or \
test_str_replace_expr_scalar or \
test_str_replace_expr_scalar or \
test_str_replace_expr_scalar or \
test_str_slice or \
test_str_slice or \
test_str_split or \
test_str_split or \
test_str_strip_chars or \
test_str_strip_chars or \
test_str_tail or \
test_str_to_lowercase or \
test_str_to_lowercase or \
test_str_to_titlecase_expr or \
test_str_to_uppercase or \
test_str_zfill or \
test_string or \
test_subtract_expr or \
test_suffix or \
test_suffix_after_alias or \
test_suffix_after_alias or \
test_sumh or \
test_sumh_aggregations or \
test_sumh_all or \
test_sumh_broadcasting or \
test_sumh_nullable or \
test_sumh_transformations or \
test_timestamp_dates or \
test_timestamp_dates or \
test_timestamp_dates or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_datetimes_tz_aware or \
test_timestamp_invalid_date or \
test_to_date or \
test_to_date_infer_fmt_expr or \
test_to_date_with_fmt_expr or \
test_to_datetime or \
test_to_datetime_infer_fmt or \
test_to_datetime_infer_fmt or \
test_to_datetime_infer_fmt or \
test_to_datetime_infer_fmt_from_date or \
test_to_datetime_tz_aware or \
test_to_datetime_tz_aware or \
test_to_lowercase or \
test_to_lowercase_after_alias or \
test_to_uppercase or \
test_to_uppercase_after_alias or \
test_top_k or \
test_top_k_by_multiple or \
test_top_level_len or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate or \
test_truncate_invalid_interval or \
test_truncate_invalid_multiple or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_truncate_multiples or \
test_tz_aware or \
test_unary or \
test_unique or \
test_unique or \
test_unique_3069 or \
test_unique_expr or \
test_unique_expr_agg or \
test_unique_first_last or \
test_unique_first_last or \
test_unique_first_last_no_subset or \
test_unique_first_last_no_subset or \
test_unique_full_subset or \
test_unique_full_subset or \
test_unique_full_subset or \
test_unique_full_subset or \
test_unique_invalid or \
test_unique_none or \
test_value_expression or \
test_when or \
test_when_otherwise or \
test_when_then_broadcasting or \
test_when_then_empty or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_select or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_aggregate_with_columns or \
test_when_then_otherwise_both_lit or \
test_when_then_otherwise_into_expr or \
test_when_then_otherwise_lit_str or \
test_when_then_otherwise_multi_output or \
test_with_columns_dtypes_single_row or \
test_with_columns_missing_column or \
test_with_columns_order or \
test_with_columns_order_single_row \
>>>>>>> origin/main
"

pytest narwhals/tests \
  -p pytest_constructor_override \
  -p env \
  --use-external-constructor \
  --constructors daft \
  -k "not ( \
      ${TESTS_THAT_NEED_FIX} \
  )" \
  "$@"
